### PR TITLE
Created a dusk test file for browser testing

### PR DESCRIPTION
**Pull request by chandresh1339**
After installation of orchestral/testbench-dusk,created a browser test file

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue).
- [ ] Breaking change (fix or feature that would cause existing functionality to change).
- [ ] New feature (non-breaking change which adds functionality).

### Final checklist

- [ ] My change requires a change to the documentation.
- [ ] I have read the contribute guideline.

### CODE REVIEW

**Comment by indpurvesh** [comment]
@chandresh1339 

If you have a time can you do a basic login test too?

**Comment by chandresh1339** [comment]
@indpurvesh,I wish you can accept my first PR and then I will commit the changes for login. I found your project very interesting and productive.

**Comment by indpurvesh** [comment]
@chandresh1339 

Sure i will merge this PR

**Comment by chandresh1339** [comment]
@indpurvesh, Thanks. I will work on the basic login test part.

**Comment by indpurvesh** [comment]
Thanks

**Pull request merged**
