### PR TITLE
add greek translation

### PR DESCRIPTION
**Pull request by nextdoorpanda**

### CODE REVIEW

**Comment by indpurvesh** [comment]
Good work. @nextdoorpanda

**Comment by indpurvesh** [comment]
@nextdoorpanda would be much helpful if you could do it on the backend framework too. 

https://github.com/avored/framework

**Comment by nextdoorpanda** [comment]
@indpurvesh Sure! Could you please tell me which files should I translate?

**Comment by indpurvesh** [comment]
@nextdoorpanda  My target is to keep all the translations in one file.

**Comment by nextdoorpanda** [comment]
> @nextdoorpanda My target is to keep all the translations in one file.

so, it's just `system.php`, right?
Should I create a new folder named after the `ISO_639-1` language name (in this case el) and place the translated `system.php` file, inside?

**Comment by indpurvesh** [comment]
Yes, you right. @nextdoorpanda

**Pull request merged**
