### PR TITLE
Developed

### PR DESCRIPTION
**Pull request by AlexMalikov94**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue).
- [ ] Breaking change (fix or feature that would cause existing functionality to change).
- [x] New feature (non-breaking change which adds functionality).

### Final checklist

- [ ] My change requires a change to the documentation.
- [ ] I have read the contribute guideline.

### CODE REVIEW

**Comment by indpurvesh** [comment]
@AlexMalikov94 

I have added some translation into a code review. If you can do it that then i will merge it.

**Comment by AlexMalikov94** [comment]
@indpurvesh  I will see your translate part as soon as possible.

**Comment by AlexMalikov94** [comment]
We reopen the pull requests, need time to see.  I just have work in another direction your project

**Comment by indpurvesh** [comment]
@AlexMalikov94 

it's been merged so you can do another PR on `developed` branch.

**Pull request merged**
