### PR TITLE
Update Composer.json

### PR DESCRIPTION
**Pull request by JunaidJaved8461**
Composer.json file (vendor/avored/framework/composer.json) for Upgraded Laravel 8

Composer.json Successfully updated for laravel version 8 updation
## Description

Updated the related packages according to laravel 8 docs

While Updating to Laravel 8 version, Error occur that has resolved by changing in handler.php file that will be done in next commit

## How To Test This

Test it by running command "composer update"
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue).
- [ ] Breaking change (fix or feature that would cause existing functionality to change).
- [ ] New feature (non-breaking change which adds functionality).

### Final checklist

- [ ] My change requires a change to the documentation.
- [ ] I have read the contribute guideline.

### CODE REVIEW

**Comment by JunaidJaved8461** [comment]
@indpurvesh Please check this pull request now!! 
Thanks

**Comment by AlexMalikov94** [comment]
@JunaidJaved8461  You need to create a developed branch. ```git checkout -b developed```

**Comment by AlexMalikov94** [comment]
@JunaidJaved8461 You have conflicts in this pull request please fix this and it will merge.

**Comment by indpurvesh** [comment]
Here are the steps that you have to follow:

 - Step 1 fork this repository [AvoRed Frameowkr](https://github.com/avored/framework)

 - Step 2  update the composer.json

       "require" : {
		"php" : ">=7.3.5",
		"symfony/yaml": "^4.2",
		"laravel/passport": "^7.4|^8.0|^9.0",
		"barryvdh/laravel-dompdf": "^0.8.4",
		"laravel/helpers": "^1.1",
		"laravel/framework" : "^5.8.15|^6.0|^7.0|^8.0",
		"rebing/graphql-laravel": "^5.1",
		"laravel/ui": "^2.0|^1.0"
	},


 - Step 3 Update the Github actions: `.github/workflows/avored-test.yml`



       name: "Run Tests"

          on: [push, pull_request]

        jobs:
            test:
                runs-on: ubuntu-latest
                   strategy:
                 fail-fast: true
              matrix:
        # php: ['7.3', '7.4']
             php: ['7.3']
               laravel: ['5.8.*', '6.*', '7.*', '8.*']
              include:
               - laravel: '5.8.*'
                 testbench: '3.8.*'
               - laravel: '6.*'
                 testbench: '4.*'
               - laravel: '7.*'
                 testbench: '5.*'
              - laravel: '8.*'
                testbench: '6.*'

**Comment by indpurvesh** [comment]
@JunaidJaved8461 

i am closing this PR

**Pull request closed without merging**
